Update midi-trigger.ttl
Looks to be needed to instantiate the plugin.
If not, I'm getting:
```
$ jalv.gtk https://github.com/metachronica/audio-dsp-midi-trigger
Plugin:       https://github.com/metachronica/audio-dsp-midi-trigger
error: failed to expand CURIE `foaf:name'
error: /usr/lib/lv2/midi-trigger.lv2/midi-trigger.ttl:14:34: expected `]', not `,'
lilv_world_load_file(): error: Error loading file `file:///usr/lib/lv2/midi-trigger.lv2/midi-trigger.ttl'
No appropriate UI found
JACK Name:    MIDI Trigger
Block length: 256 frames
MIDI buffers: 32768 bytes
Comm buffers: 524288 bytes
Update rate:  25,0 Hz
Failed to instantiate plugin.
```